### ISSUE TITLE
Sap access cluster

### ISSUE THREAD

**Issue by durlaniulian** [jsoumelidis/php_sap#4]
Hello again @jsoumelidis .

Can you have any ideea how can i access clusters in sap using rfc?
I want to acces Payroll Results Table (RT) and Time evaluation results tables (ZES, SALDO).

With your php extension i can't call programs or transaction, am I right?

Thx.

**Comment by jsoumelidis** [comment]
Hello @durlaniulian,
This extension is used to invoke remote enabled functions only, you cannot
directly call programs like in SE38. I would suggest to “wrap” the program
you want to run in a new remote enabled function and then call that with
php!
I don’t understand what you mean by “cluster” tables, but if you want to
directly read a sap database table you can use the SapRfcReadTable class or
the SAP built in RFC_READ_TABLE remote enabled function. You can read more
about this special functionality at the classes and/or examples folder of
the repository.
